### ISSUE TITLE
Linux support missing

### ISSUE THREAD

**Issue by DavidCGranger** [SkyVerseMc/Legacy-Minecraft-Launcher#1]
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,

        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
        at java.desktop/java.awt.Window.<init>(Window.java:553)
        at java.desktop/java.awt.Frame.<init>(Frame.java:428)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:224)
        at net.minecraft.bootstrap.Bootstrap.<init>(Bootstrap.java:82)
        at net.minecraft.bootstrap.Bootstrap.main(Bootstrap.java:449)

**Comment by DavidCGranger** [comment]
This confuses me, as the old launcher obviously officially supported it.

**Comment by DavidCGranger** [comment]
It seems my Java install was broken, sorry.
